version: '3.3'
services:
    dp-cantabular-dimension-api:
        build:
            context: ../..
            dockerfile: Dockerfile.local
        command:
            - go 
            - test 
            - -cover 
            - -race
            - -coverpkg=github.com/ONSdigital/dp-cantabular-dimension-api/... 
            - -component
        volumes:
            - ../../:/dp-cantabular-dimension-api
        ports:
            - 27200:27200
        environment:
            BIND_ADDR:                   ":27200"
            COMPONENT_TEST_USE_LOG_FILE: "${COMPONENT_TEST_USE_LOG_FILE-false}"
            ENABLE_PRIVATE_ENDPOINTS:    "false"
            ENABLE_PERMISSIONS_AUTH:     "false"
