swagger: "2.0"
basePath: "/v1"
info:
  description: ""
  version: "1.0.0"
  title: "Query geography"
schemes:
- "http"
paths:
  /dimensions:
    get:
      summary: "Get list of geography dimensions for given Dataset "
      description: ""
      produces:
      - "application/json"
      parameters:
        - name: dataset
          type: string
          in: query
          required: true
      responses:
        200:
          description: "dimensions returned successfully"
          schema:
            $ref: '#/definitions/GetDimensionsResponse'
  /dimension/{dimension}/options:
    get:
      summary: "Get list of options for given dimension "
      description: ""
      produces:
      - "application/json"
      parameters:
        - name: dimension
          type: string
          in: path
          required: true
      responses:
        200:
          description: "area types returned successfully"
          schema:
            $ref: '#/definitions/GetDimensionOptionsResponse'
responses:
  Unauthorised:
    description: "The token provided is unauthorised to carry out this operation"
  InternalServerError:
    description: "Failed to process the request due to an internal error"
  BadGateway:
    description: "Failed to process the request due to an error in a downstream server"
definitions:
  GetDimensionsResponse:
    description: "The response body containing dimensions for a given dataset"
    properties:
      dimensions:
        type: array
        items:
          $ref: '#/definitions/Dimension'
        example: 
        - name: "city"
          code_list:
            href: "http://localhost:22400/code-lists/city"
            id: "city"
          options:
            href: "http://localhost:22000/datasets/example-1/editions/2021/versions/1/dimensions/city/options"
            id: "city"
          version:
            href: "http://localhost:22000/datasets/example-1/editions/2021/versions/1"
        - name: "region"
          code_list:
            href: "http://localhost:22400/code-lists/region"
            id: "region"
          options:
            href: "http://localhost:22000/datasets/example-1/editions/2021/versions/1/dimensions/region/options"
            id: "city"
          version:
            href: "http://localhost:22000/datasets/example-1/editions/2021/versions/1"
  GetDimensionOptionsResponse:
    description: "The response body containing options for a given Dimension"
    properties:
      options:
        type: array
        items:
          $ref: '#/definitions/DimensionOption'
        example: 
        - label: "Liverpool"
          code_list:
            href: "http://localhost:22400/code-lists/city"
            id: "city"
          code:
            href: "http://localhost:22400/code-lists/city/codes/1"
            id: "1"
          version:
            href: "http://localhost:22000/datasets/example-1/editions/2021/versions/1"            
        - name: "Belfast"
          code_list:
            href: "http://localhost:22400/code-lists/city"
            id: "city"
          code:
            href: "http://localhost:22400/code-lists/city/codes/2"
            id: "2"
          version:
            href: "http://localhost:22000/datasets/example-1/editions/2021/versions/1"
  Dimension:
    properties:
      name:
        type: string
      links:
        type: object
        properties:
          code_list:
            type: object
            properties:
              href:
                type: string
              id:
                type: string
          options:
            type: object
            properties:
              href:
                type: string
              id:
                type: string
          version:
            type: object
            properties:
              href:
                type: string
  DimensionOption:
    properties:
      name:
        type: string
      links:
        type: object
        properties:
          code_list:
            type: object
            properties:
              href:
                type: string
              id:
                type: string
          code:
            type: object
            properties:
              href:
                type: string
              id:
                type: string
          version:
            type: object
            properties:
              href:
                type: string
