---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: latest

inputs:
  - name: dp-cantabular-dimension-api

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-cantabular-dimension-api/ci/scripts/build.sh
